## Loading the libraries
library(tidyverse)
library(caret)

## Loading the data
dl <- tempfile()
download.file("http://files.grouplens.org/datasets/movielens/ml-10m.zip", dl)

ratings <- read.table(text = gsub("::", "\t", readLines(unzip(dl, "ml-10M100K/ratings.dat"))), col.names = c("userId", "movieId", "rating", "timestamp"))

movies <- str_split_fixed(readLines(unzip(dl, "ml-10M100K/movies.dat")), "\\::", 3)
colnames(movies) <- c("movieId", "title", "genres")
movies <- as.data.frame(movies) %>% mutate(movieId = as.numeric(levels(movieId))[movieId],
                                           title = as.character(title),
                                           genres = as.character(genres))

movielens <- left_join(ratings, movies, by = "movieId")

# Validation set will be 10% of MovieLens data

set.seed(1)
test_index <- createDataPartition(y = movielens$rating, times = 1, p = 0.1, list = FALSE)
edx <- movielens[-test_index,]
temp <- movielens[test_index,]

# Make sure userId and movieId in validation set are also in edx set

validation <- temp %>% 
    semi_join(edx, by = "movieId") %>%
    semi_join(edx, by = "userId")

# Add rows removed from validation set back into edx set

removed <- anti_join(temp, validation)
edx <- rbind(edx, removed)

rm(dl, ratings, movies, test_index, temp, movielens, removed)

## Preprocessing
set.seed(135)

#Creating training and testing data sets
test_index <- createDataPartition(y = edx$rating, times = 1, p = 0.1, list = FALSE)
train <- edx[-test_index,]
temp <- edx[test_index,]

test <- temp %>% 
semi_join(train, by = "movieId") %>%
semi_join(train, by = "userId")

## take observations removed from test and add to train
removed <- anti_join(temp, test)
train <- rbind(train, removed)
rm(temp)
```

## Modelling
## Using cross-validation using test data to find the best value of lambda
lambdas <- seq(0, 10, 0.25)

rmses <- sapply(lambdas, function(l){
    
    mu <- mean(train$rating)
    
    b_i <- train %>% 
        group_by(movieId) %>%
        summarize(b_i = sum(rating - mu)/(n()+l))
    
    b_u <- train %>% 
        left_join(b_i, by="movieId") %>%
        group_by(userId) %>%
        summarize(b_u = sum(rating - b_i - mu)/(n()+l))
    
    predicted_ratings <- 
        test %>% 
        left_join(b_i, by = "movieId") %>%
        left_join(b_u, by = "userId") %>%
        mutate(pred = mu + b_i + b_u) %>%
        pull(pred)
    
    return(RMSE(predicted_ratings, test$rating))
})

## Calculating the value of lambda for which RMSE is minumum on test data
qplot(lambdas, rmses)
lambda <- lambdas[which.min(rmses)]
lambda
min(rmses)

## Creating the final model using validation data set
b_i <- train %>% 
    group_by(movieId) %>%
    summarize(b_i = sum(rating - mu)/(n()+lambda))

b_u <- train %>% 
    left_join(b_i, by="movieId") %>%
    group_by(userId) %>%
    summarize(b_u = sum(rating - b_i - mu)/(n()+lambda))

final_predicted_ratings <- 
    validation %>% 
    left_join(b_i, by = "movieId") %>%
    left_join(b_u, by = "userId") %>%
    mutate(pred = mu + b_i + b_u) %>%
    pull(pred)

## Calculating final RMSE on validation data set
final_rmse <- RMSE(final_predicted_ratings, validation$rating)